source :rubygems
gem 'activerecord'
gem 'rack-test'
gem 'mysql'
gem 'daemons'
gem 'rake'
gem 'passenger', '2.2.15'
gem 'authlogic'
gem 'authlogic_pam'
gem 'rpam'
gem 'rack'
gem 'nokogiri'
gem 'activesupport'
gem 'actionpack'
gem 'webrat'
gem 'cucumber'
gem 'mime-types'
