#!/bin/sh
### BEGIN INIT INFO
# Provides:          opengov
# Required-Start:    $local_fs $remote_fs apache2
# Required-Stop:     $local_fs $remote_fs apache2
# Default-Start:     2 3 4 5
# Default-Stop:      S 0 1 6
# Short-Description: opengov initscript
# Description:       opengov
### END INIT INFO

# Adaped by: Larry Reaves
# From thin init script
# Original author: Forrest Robertson

# Do NOT "set -e"

DAEMON=/var/www/opengov/control.rb
SCRIPT_NAME=/etc/init.d/opengov
#USER=www-data
USER=root

# Exit if the package is not installed
[ -x "$DAEMON" ] || exit 0

case "$1" in
  start)
	mkdir -p /tmp/opengov
        su -c "$DAEMON -pm start" $USER
        ;;
  stop)
        su -c "$DAEMON -pm stop" $USER
        ;;
  restart)
        su -c "$DAEMON -pm stop" $USER
	sleep 5
	su -c "$DAEMON -pm start" $USER
        ;;
  status)
	su -c "$DAEMON -pm status" $USER
	;;
  *)
        echo "Usage: $SCRIPT_NAME {start|status|stop|restart}" >&2
        exit 3
        ;;
esac

:
