--- 
chdir: /var/www/opengov
environment: production
address: 127.0.0.1
port: 3000
timeout: 30
log: log/thin.log
pid: tmp/pids/thin.pid
max_conns: 1024
max_persistent_conns: 512
require: []

wait: 30
servers: 1
user: www-data
group: www-data
daemonize: true

rackup: /var/www/opengov/router.ru