module Derailed
  module API
    ##
    # Feature: RackRequestResponder API
    #   As a component developer
    #   In order to allow my component to respond to a RackRequest
    #   I want to allow responding to the request identified by the key
    ##
    module RackRequestResponder
      # request_response(key) -> [status, headers,body] to Rack spec
      # key is generated by the Component's Manager when RackApp
      # calls initiate_request
      def request_response; end
    end
  end
end
