module Derailed
  module API
    ##
    # Feature: RackRequestResponder API
    #   As a component developer
    #   In order to allow my component to respond to a RackRequest
    #   I want to fetch the response for the key
    ##
    module RackRequestResponder
      ##
      # Scenario Outline: fetch the response for the key
      # fetch_response(key) -> [status, headers,body] to Rack spec
      # key is generated by the Component's Manager when RackApp
      # calls request_response
      def fetch_response; end
    end
  end
end
